# ********** Please don't edit this file!
# ********** It has been generated automatically by dae_devops version 0.5.2.dev0+g83ac02a.d20230224.
# ********** For repository_name dls-multiconf

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

# dae_devops_fingerprint e3466146c814c7c3791809e72b02daac
