# Primary information needed for devops.
primary:
    repository_name: dls-multiconf
    package_name: dls_multiconf_lib
    one_line_description: "Python class for runtime configuration coordinating multiple services."
    author:
        name: David Erb
        email: david.erb@diamond.ac.uk
    project_urls:
        GitLab: https://github.com/diamondlightsource/dls-multiconf
    project_scripts:
        dls-multiconf: "dls_multiconf_lib.__main__:main"
    dependencies:
        - type: pypi
          list:
              - ruamel.yaml
